/* ============================================================
   Shore Roleplay — Official Email Communication System
   Classification: INTERNAL • DO NOT DISTRIBUTE
   ============================================================ */

const BRAND = {
  name: "Shore Roleplay",
  logo: "https://i.imgur.com/P15LI6g.png", // SERVER LOGO
  color: "#4EA3FF",
  bg: "#070b12",
  text: "#d7dde7",
  success: "#27ae60",
  denied: "#c0392b",
  discord: "https://discord.gg/KJdnacyDXA",
  website: "https://shoreroleplay.xyz",
};

/* ============================================================
   UNIVERSAL TEMPLATE WRAPPER
============================================================ */
function wrap(body, accent = BRAND.color, header = "Notification") {
  return `
  <div style="background:${BRAND.bg};padding:45px 0;font-family:'Segoe UI',sans-serif;">
    <table role="presentation" width="100%" cellspacing="0" cellpadding="0">
      <tr><td align="center">

        <table role="presentation" width="640"
          style="background:#0d1119;border-radius:14px;overflow:hidden;
          box-shadow:0 0 30px rgba(0,0,0,.55);border:1px solid rgba(255,255,255,.06);">

          <!-- LOGO -->
          <tr>
            <td style="background:#0d1119;text-align:center;padding:28px 0;">
              <img src="${BRAND.logo}" alt="${BRAND.name} Logo"
                style="display:block;margin:auto;width:165px;max-width:85%;
                filter:drop-shadow(0 0 12px rgba(78,163,255,.55));">
            </td>
          </tr>

          <!-- HEADER -->
          <tr>
            <td style="background:${accent};padding:32px;color:white;
              font-size:27px;font-weight:700;text-align:center;letter-spacing:.6px;">
              ${BRAND.name} — ${header}
            </td>
          </tr>

          <!-- BODY -->
          <tr>
            <td style="padding:45px;color:${BRAND.text};font-size:16px;line-height:1.7;">
              ${body}
            </td>
          </tr>

          <!-- FOOTER -->
          <tr>
            <td style="padding:24px;text-align:center;font-size:12px;color:#7e8897;background:#0b0f16;">
              This correspondence was generated by the ${BRAND.name} Automated System.<br>
              <span style="opacity:.6">Do not reply to this email. For support, use our Discord ticket system.</span>
            </td>
          </tr>

        </table>

      </td></tr>
    </table>
  </div>`;
}

/* ============================================================
   EMAIL — ACCOUNT VERIFICATION (NEW)
============================================================ */
function verifyEmail({ username, token }) {
  return wrap(`
    <h2 style="margin-top:0;color:${BRAND.color};font-size:24px;">
      Verify Your Account — ${username}
    </h2>

    <p>Thank you for registering with <strong>${BRAND.name}</strong>.</p>

    <p>Your account is <strong>not active</strong> yet. To complete your registration and gain access, you must verify your email.</p>

    <p style="margin-top:12px;">Click the secure button below to finalize your account creation:</p>

    <div style="margin-top:32px;text-align:center;">
      <a href="${BRAND.website}/verify.html?token=${token}"
         style="display:inline-block;padding:16px 42px;background:${BRAND.color};
         color:white;border-radius:8px;text-decoration:none;font-weight:700;font-size:16px;">
         ✔ Verify My Account
      </a>
    </div>

    <p style="margin-top:22px;font-size:14px;opacity:.85;">
      If you did not create an account with us, no action is required.
    </p>
  `, BRAND.color, "Email Verification");
}

/* ============================================================
   EMAIL — APPLICATION APPROVED
============================================================ */
function acceptedEmail({ username }) {
  return wrap(`
    <h2 style="margin-top:0;color:${BRAND.success};font-size:24px;">Application Approved — ${username}</h2>

    <p>Your application for membership within <strong>${BRAND.name}</strong> has undergone full review and has been
    <strong style="color:${BRAND.success}">APPROVED</strong>.</p>

    <p>You are now authorized to participate in official community operations. You are expected to comply with all directives and remain within the Discord server.</p>

    <div style="margin-top:35px;text-align:center;">
      <a href="${BRAND.discord}"
         style="display:inline-block;padding:14px 32px;background:${BRAND.success};
         color:white;border-radius:8px;text-decoration:none;font-weight:600;font-size:15px;">
         Proceed to Operational Channels
      </a>
    </div>
  `, BRAND.success, "Application Result");
}

/* ============================================================
   EMAIL — APPLICATION DENIED
============================================================ */
function deniedEmail({ username }) {
  return wrap(`
    <h2 style="margin-top:0;color:${BRAND.denied};font-size:24px;">Application Status — ${username}</h2>

    <p>Your application to join <strong>${BRAND.name}</strong> has been
    <strong style="color:${BRAND.denied}">DENIED</strong>.</p>

    <p>You remain in the Discord server but are not authorized for whitelisted activity.</p>

    <div style="margin-top:35px;text-align:center;">
      <a href="${BRAND.website}/public/apply.html"
         style="display:inline-block;padding:14px 32px;background:${BRAND.denied};
         color:white;border-radius:8px;text-decoration:none;font-weight:600;font-size:15px;">
         Submit Revised Application
      </a>
    </div>
  `, BRAND.denied, "Application Result");
}

module.exports = {
  verifyEmail,
  acceptedEmail,
  deniedEmail
};
