/* ============================================================
   Shore Roleplay — Official Application Communication System
   Classification: INTERNAL • DO NOT DISTRIBUTE
   ============================================================ */

const BRAND = {
  name: "Shore Roleplay",
  logo: "https://i.imgur.com/P15LI6g.png",  // <-- YOUR LOGO
  color: "#4EA3FF",
  bg: "#070b12",
  text: "#d7dde7",
  success: "#27ae60",
  denied: "#c0392b",
  discord: "https://discord.gg/KJdnacyDXA",
  website: "https://shoreroleplay.xyz",
};

/* UNIVERSAL TEMPLATE WRAPPER */
function wrap(body, accent = BRAND.color) {
  return `
  <div style="background:${BRAND.bg};padding:45px 0;font-family:'Segoe UI',sans-serif;">
    <table role="presentation" width="100%" cellspacing="0" cellpadding="0">
      <tr><td align="center">

        <table role="presentation" width="640" style="background:#0d1119;border-radius:14px;overflow:hidden;box-shadow:0 0 30px rgba(0,0,0,.55);border:1px solid rgba(255,255,255,.06);">

          <!-- LOGO -->
          <tr>
            <td style="background:#0d1119;text-align:center;padding:28px 0;">
              <img src="${BRAND.logo}" alt="${BRAND.name} Logo"
                style="display:block;margin:auto;width:165px;max-width:85%;filter:drop-shadow(0 0 12px rgba(78,163,255,.55));">
            </td>
          </tr>

          <!-- HEADER -->
          <tr>
            <td style="background:${accent};padding:32px;color:white;font-size:27px;font-weight:700;text-align:center;letter-spacing:.6px;">
              ${BRAND.name} — Application Notification
            </td>
          </tr>

          <!-- BODY -->
          <tr>
            <td style="padding:45px;color:${BRAND.text};font-size:16px;line-height:1.7;">
              ${body}
            </td>
          </tr>

          <!-- FOOTER -->
          <tr>
            <td style="padding:24px;text-align:center;font-size:12px;color:#7e8897;background:#0b0f16;">
              This correspondence was generated by the ${BRAND.name} Automated Personnel System.<br>
              <span style="opacity:.6">Do not reply. All communication must be handled via Discord support channels.</span>
            </td>
          </tr>

        </table>

      </td></tr>
    </table>
  </div>`;
}

/* ACCEPTED TEMPLATE */
function acceptedEmail({ username }) {
  return wrap(`
    <h2 style="margin-top:0;color:${BRAND.success};font-size:24px;">Application Approved — ${username}</h2>

    <p>Your application for membership within <strong>${BRAND.name}</strong> has undergone full review and has been
    <strong style="color:${BRAND.success}">APPROVED</strong>.</p>

    <p>As an approved participant, you are now authorized to engage in official community operations. You are expected to comply with all staff directives and remain within our Discord server at all times.</p>

    <p style="margin-top:16px;">Welcome to the operational environment. Misconduct, rule violations, or unauthorized conduct may result in suspension or permanent removal.</p>

    <div style="margin-top:35px;text-align:center;">
      <a href="${BRAND.discord}"
         style="display:inline-block;padding:14px 32px;background:${BRAND.success};color:white;border-radius:8px;text-decoration:none;font-weight:600;font-size:15px;">
         Proceed to Operational Channels
      </a>
    </div>

    <p style="font-size:14px;margin-top:22px;opacity:.85;">We look forward to your contributions.</p>
  `, BRAND.success);
}

/* DENIED TEMPLATE */
function deniedEmail({ username }) {
  return wrap(`
    <h2 style="margin-top:0;color:${BRAND.denied};font-size:24px;">Application Status — ${username}</h2>

    <p>Your application to join <strong>${BRAND.name}</strong> has been reviewed and has been
    <strong style="color:${BRAND.denied}">DENIED</strong>.</p>

    <p>The evaluation determined that one or more required standards were not met. You remain within the Discord server, but are not authorized to participate in whitelist operations.</p>

    <p style="margin-top:16px;">Should you choose to reapply, ensure that your submission reflects a complete and compliant understanding of our expectations and environment.</p>

    <div style="margin-top:35px;text-align:center;">
      <a href="${BRAND.website}/apply"
         style="display:inline-block;padding:14px 32px;background:${BRAND.denied};color:white;border-radius:8px;text-decoration:none;font-weight:600;font-size:15px;">
         Submit Revised Application
      </a>
    </div>

    <p style="margin-top:22px;font-size:14px;opacity:.85;">
      Direct any clarification requests through designated Discord support channels.
    </p>
  `, BRAND.denied);
}

module.exports = { acceptedEmail, deniedEmail };
