/* ============================================================
   Shore Roleplay — Official Application Communication System
   Classification: INTERNAL • DO NOT DISTRIBUTE
   ============================================================ */

const BRAND = {
  name: "Shore Roleplay",
  color: "#4EA3FF",
  bg: "#070b12",
  text: "#d7dde7",
  success: "#27ae60",
  denied: "#c0392b",
  discord: "https://discord.gg/KJdnacyDXA", // already joined
  website: "https://shoreroleplay.xyz",
};

/* UNIVERSAL TEMPLATE WRAPPER */
function wrap(body, accent = BRAND.color) {
  return `
  <div style="background:${BRAND.bg};padding:45px 0;font-family:'Segoe UI',sans-serif;">
    <table role="presentation" width="100%" cellspacing="0" cellpadding="0">
      <tr><td align="center">

        <table role="presentation" width="640" style="background:#0d1119;border-radius:14px;overflow:hidden;box-shadow:0 0 30px rgba(0,0,0,.55);border:1px solid rgba(255,255,255,.06);">

          <!-- HEADER -->
          <tr>
            <td style="background:${accent};padding:32px;color:white;font-size:27px;font-weight:700;text-align:center;letter-spacing:.6px;">
              ${BRAND.name} — Application Notification
            </td>
          </tr>

          <!-- BODY -->
          <tr>
            <td style="padding:45px;color:${BRAND.text};font-size:16px;line-height:1.7;">
              ${body}
            </td>
          </tr>

          <!-- FOOTER -->
          <tr>
            <td style="padding:24px;text-align:center;font-size:12px;color:#7e8897;background:#0b0f16;">
              This correspondence was generated by the ${BRAND.name} Automated Personnel System.<br>
              <span style="opacity:.6">Do not reply. Questions must be directed through the Discord support channels.</span>
            </td>
          </tr>

        </table>

      </td></tr>
    </table>
  </div>`;
}

/* ============================================================
   ACCEPTED TEMPLATE
   ============================================================ */
function acceptedEmail({ username }) {
  return wrap(`
    <h2 style="margin-top:0;color:${BRAND.success};font-size:24px;">Application Approved — ${username}</h2>

    <p>Your application for membership within <strong>${BRAND.name}</strong> has undergone full review and has been
    <strong style="color:${BRAND.success}">APPROVED</strong>.</p>

    <p>As an approved member, you are now officially recognized within our operational structure. You are expected to
    remain inside our Discord at all times, comply with staff directives, and uphold the standards of conduct outlined in our regulations.</p>

    <p style="margin-top:16px;">You may now proceed with in-community operations. Failure to comply with rules or policy may result in disciplinary action, up to and including removal from ${BRAND.name}.</p>

    <div style="margin-top:35px;text-align:center;">
      <a href="${BRAND.discord}" 
         style="display:inline-block;padding:14px 32px;background:${BRAND.success};color:white;border-radius:8px;
         text-decoration:none;font-weight:600;font-size:15px;">
         Proceed to Operational Channels
      </a>
    </div>

    <p style="font-size:14px;margin-top:22px;opacity:.85;">Welcome aboard.</p>
  `, BRAND.success);
}

/* ============================================================
   DENIED TEMPLATE
   ============================================================ */
function deniedEmail({ username }) {
  return wrap(`
    <h2 style="margin-top:0;color:${BRAND.denied};font-size:24px;">Application Status — ${username}</h2>

    <p>Your application for entry into <strong>${BRAND.name}</strong> has been reviewed and has
    <strong style="color:${BRAND.denied}">NOT been approved</strong>.</p>

    <p>This determination was based on one or more criteria not being met. You remain a member of the Discord, but are not authorized to participate in whitelist operations or departmental activity.</p>

    <p>If you intend to re-apply, ensure that your responses reflect a clear understanding of our standards, expectations, and your intended role within the community.</p>

    <div style="margin-top:35px;text-align:center;">
      <a href="${BRAND.website}/apply"
         style="display:inline-block;padding:14px 32px;background:${BRAND.denied};color:white;border-radius:8px;
         text-decoration:none;font-weight:600;font-size:15px;">
         Submit a Revised Application
      </a>
    </div>

    <p style="margin-top:22px;font-size:14px;opacity:.85;">
      You may contact staff through proper support channels for clarification before attempting again.
    </p>
  `, BRAND.denied);
}

module.exports = { acceptedEmail, deniedEmail };
